# Generated by Django 2.1.3 on 2018-11-14 14:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181114_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='height',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0'), max_digits=5),
        ),
    ]
