# Generated by Django 2.1.3 on 2018-12-01 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181130_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='activity',
            field=models.CharField(blank=True, choices=[('S', 'Sédentaire '), ('P', 'Peu actif '), ('A', 'Actif '), ('T', 'Très acitf ')], max_length=1),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='diet',
            field=models.CharField(blank=True, choices=[('A', 'Aucun'), ('H', 'Hyperprotéiné '), ('P', 'Protéiné '), ('C', 'Hypercalorique '), ('D', 'Dissocié '), ('V', 'Végétarien '), ('S', 'Sans sel '), ('N', 'Anticellulite '), ('G', 'Hypoglucidique '), ('X', 'Détox ')], max_length=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
    ]
