# Generated by Django 2.1.3 on 2018-12-02 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20181130_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='diet',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
