# Generated by Django 2.1.3 on 2018-12-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20181202_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='diet',
            field=models.CharField(choices=[('hyperprotéiné', 'HYPP'), ('protéiné', 'PROT'), ('hypocalorique', 'HYPC'), ('Dissocié', 'DISS'), ('végétarien', 'VEGE'), ('anticellulite', 'ANTI'), ('sans sel', 'SSEL'), ('hypoglucidique', 'HYPG'), ('detox', 'DETX'), ('aucun régime', 'NONE')], default='aucun régime', max_length=4),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('Femme', 'F'), ('Homme', 'H'), ('Indefini', 'I')], default='Indefini', max_length=1),
        ),
    ]
