# Generated by Django 2.1.3 on 2018-11-30 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recette',
            name='nbCalories',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recette',
            name='nombre_part',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recette',
            name='recette',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recette',
            name='recette_instructions',
            field=models.TextField(default='Instructions', max_length=1000),
            preserve_default=False,
        ),
    ]
