# Generated by Django 2.1.3 on 2018-11-30 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0002_auto_20181130_1341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recette',
            old_name='recette',
            new_name='author',
        ),
    ]
