# Generated by Django 2.1.3 on 2018-11-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0003_auto_20181130_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='recette',
            name='image',
            field=models.ImageField(default='static/Recipes/default_recipe_img.jpg', upload_to='Recipes'),
        ),
    ]
