# Generated by Django 2.1.3 on 2018-11-30 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0004_recette_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recette',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recette',
            name='image',
            field=models.ImageField(blank=True, default='static/Recipes/default_recipe_img.jpg', null=True, upload_to='Recipes'),
        ),
        migrations.AlterField(
            model_name='recette',
            name='nbCalories',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='recette',
            name='recette_instructions',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
