# Generated by Django 2.1.3 on 2018-11-30 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0005_auto_20181130_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recette',
            name='image',
        ),
    ]
