# Generated by Django 2.1.3 on 2018-11-30 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0006_remove_recette_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recette',
            name='image',
            field=models.URLField(blank=True, default='https://cb2.scene7.com/is/image/CB2/BlackClayDinnerPlate11inSHF16/?$web_product_hero$&161208101132&wid=625&hei=625', null=True),
        ),
    ]
