# Generated by Django 2.0.2 on 2018-12-01 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0008_auto_20181130_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carbohydrates_100g', models.TextField(blank=True, null=True)),
                ('energy_100g', models.TextField(blank=True, null=True)),
                ('fat_100g', models.TextField(blank=True, null=True)),
                ('fiber_100g', models.TextField(blank=True, null=True)),
                ('id_product', models.IntegerField(blank=True, null=True)),
                ('ingredients_text', models.CharField(blank=True, max_length=2083, null=True)),
                ('product_name', models.CharField(blank=True, max_length=61, null=True)),
                ('proteins_100g', models.TextField(blank=True, null=True)),
                ('quantity', models.CharField(blank=True, max_length=29, null=True)),
                ('sodium_100g', models.TextField(blank=True, null=True)),
                ('sugars_100g', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
    ]
