# Generated by Django 2.1.3 on 2018-12-02 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0009_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='id_ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Recipes.Product'),
        ),
    ]
