# Generated by Django 2.1.3 on 2018-12-02 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0010_auto_20181202_1550'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='Recipes_product',
        ),
    ]
