# Generated by Django 2.1.3 on 2018-12-02 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0011_auto_20181202_1556'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
    ]
