# Generated by Django 2.1.3 on 2018-12-02 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0012_auto_20181202_1557'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='default',
        ),
    ]
