# Generated by Django 2.1.3 on 2018-12-02 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0013_auto_20181202_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit2',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('carbohydrates_100g', models.FloatField(blank=True, null=True)),
                ('energy_100g', models.FloatField(blank=True, null=True)),
                ('fat_100g', models.FloatField(blank=True, null=True)),
                ('fiber_100g', models.FloatField(blank=True, null=True)),
                ('ingredients_text', models.CharField(blank=True, max_length=2083, null=True)),
                ('product_name', models.CharField(blank=True, max_length=61, null=True)),
                ('proteins_100g', models.FloatField(blank=True, null=True)),
                ('quantity', models.CharField(blank=True, max_length=29, null=True)),
                ('sodium_100g', models.FloatField(blank=True, null=True)),
                ('sugars_100g', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
    ]
